### ISSUE TITLE
Hue, Chroma, Luminance

### ISSUE THREAD

**Issue by mduvekot** [rstudio-conf-2022/ggplot2-graphic-design#3]
Slide 6 in "Colourful Graphics" shows a series of colours that do not have constant values for chroma and luminance in the Hue series. Chroma goes to black, not grey and the Lumimance series is not constant in hue (it's too yellow).

I have attached some code that generates a plot that illustrates the same idea, but with values for h, c and l that are  only vary for the component  to be shown, while remaining constant for all others. 
[Colourful_Graphics_hcl.R.zip](https://github.com/rstudio-conf-2022/ggplot2-graphic-design/files/12706615/Colourful_Graphics_hcl.R.zip)
![hcl](https://github.com/rstudio-conf-2022/ggplot2-graphic-design/assets/6717967/c42f7472-835d-4d79-a5eb-117900edbce4)

**Comment by z3tt** [comment]
Thanks @mduvekot for spotting this and even more for providing an R script to generate a valid example! I will update it within the next days.

**Comment by z3tt** [comment]
I've finally updated the slide, thanks for your feedback and the code once again!
![HCL](https://github.com/rstudio-conf-2022/ggplot2-graphic-design/assets/7523556/a4585a87-34a7-45cf-82a6-2dbd913d7e75)
